### PR TITLE
Dockerize backend

### PR DESCRIPTION
**Pull request by JJamesWWang**
Dockerizes the backend: 
This makes it so that you can run a local database and server with just one command: `docker-compose up`.
You should no longer need to access the production database; however, this means you must ingest SIS course data yourself. Instructions are found in the README file.

This was branched off of @DenouementX's branch iter1-lawrence, so that's why you see some changes I didn't make. 

As a follow up, we should definitely remove `localhost` from your CORS headers on the server, as well as our own API. I've also heard that there's no user authentication in the backend routes...

### CODE REVIEW

**Comment by JJamesWWang** [comment]
This isn't done yet so don't merge

**Review by MattLiu-mygit — APPROVED** [review]
Looks good! Dockerizing is pog and will help us dev safely in the backend in the future.

**Review by QinyuanWu — APPROVED** [review]
Nice! P.S. We need backend route level authentication ASAP ahhhh

**Comment by JJamesWWang** [comment]
@MattLiu-mygit I'm letting you merge this when you're ready to introduce docker to the team

**Comment by DenouementX** [comment]
Looks good! I appreciate the README updates.

**Comment by MattLiu-mygit** [comment]
> @MattLiu-mygit I'm letting you merge this when you're ready to introduce docker to the team

Sounds good; I'll hold off on it for now and will merge it in in a bit when we are ready.

**Review by DenouementX — APPROVED** [review]
Looks good! I appreciate the README updates.

**Comment by MattLiu-mygit** [comment]
DON'T DELETE BRANCH THIS WAS ACCIDENTALLY MERGED BECAUSE IM A DUMBO

**Pull request merged**
