### PR TITLE
Iter 03 e2e testing changes

### PR DESCRIPTION
**Pull request by JJamesWWang**
Adds a delete user endpoint and patches up docker

### CODE REVIEW

**Review by DenouementX — APPROVED** [review]
Looks good!

**Review by room-projector — APPROVED** [review]
Looks good!

**Review by robertzhidealx — APPROVED** [review]
LGTM

**Review by QinyuanWu — APPROVED** [review]
looks good

**Review by alanz132 — APPROVED** [review]
You're a beast

**Pull request merged**
